parameters:
#    wbriks_backend.example.class: wbriks\BackendBundle\Example

services:
#    wbriks_backend.example:
#        class: %wbriks_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
